source 'https://rubygems.org'
gemspec

gem 'mysql2'
gem 'capybara', '2.15.1'
gem 'puma'
gem 'factory_girl_rails'
gem 'pry-rails'
gem 'the_history', github: 'yigexiangfa/the_history', tag: 'v0.2.8'
gem 'default_where', github: 'qinmingyuan/default_where', tag: 'v2.0.5'
gem 'default_form', github: 'qinmingyuan/default_form', tag: 'v3.1.6'
gem 'kaminari', github: 'amatsuda/kaminari'
gem 'rails_com', github: 'qinmingyuan/rails_com', tag: 'v0.8.37'
gem 'sprockets', github: 'rails/sprockets', ref: '3c542c1'
gem 'the_data', github: 'yigexiangfa/the_data', tag: 'v1.1.2'
gem 'the_role', github: 'yigexiangfa/the_role', tag: 'v3.9.15'
