regular:
  - angle-left
  - angle-right
  - bag-shopping
  - box-archive
  - boxes-packing
  - cart-plus
  - cart-shopping
  - cash-register
  - check-double
  - chevron-right
  - circle-dollar-to-slot
  - circle-minus
  - circle-plus
  - circle-xmark
  - comments
  - gears
  - handshake
  - list
  - list-ol
  - location-dot
  - pen-clip
  - pencil
  - print
  - receipt
  - thumbs-down
  - trash
