regular:
  - angle-left
  - angle-right
  - bag-shopping
  - box-archive
  - boxes-packing
  - cart-plus
  - cart-shopping
  - cash-register
  - chevron-right
  - circle-dollar-to-slot
  - circle-minus
  - circle-plus
  - circle-xmark
  - gears
  - handshake
  - location-dot
  - pencil
  - trash
