regular:
  - angle-left
  - angle-right
  - arrow-left
  - bag-shopping
  - bars
  - box-archive
  - boxes-packing
  - cart-plus
  - cart-shopping
  - cash-register
  - check-double
  - chevron-right
  - clock-rotate-left
  - circle-dollar-to-slot
  - circle-minus
  - circle-plus
  - circle-xmark
  - comments
  - ellipsis-vertical
  - eye
  - gears
  - hand-holding-dollar
  - handshake
  - list
  - list-ol
  - location-dot
  - magnifying-glass
  - pen-clip
  - pencil
  - print
  - receipt
  - rotate
  - thumbs-down
  - trash
  - users
