Trade::Order:
  default:
    only: ['uuid', 'created_at', 'note']
  produced:
    only: ['uuid', 'created_at', 'note']
    methods: ['serial_str', 'organ_address', 'subject']
Trade::Item:
  default:
    only: ['good_name', 'number', 'amount', 'note']
    methods: ['order_uuid', 'cart_organ']
Trade::Payment:
  default:
    only: ['payment_uuid', 'created_at', 'total_amount', 'type', 'buyer_bank']
    methods: ['type_i18n']
